resource "local_file" "pet" {
  filename    = var.filename
  content = "My favorite pet is ${random_pet.my-pet.id}"
}

resource "random_pet" "my-pet" {
  prefix = var.prefix
  separator = var.separator
  length = var.length
}

# See below on how to output the variables
# This is equivalent to Write-Output in powershell or debug module in Ansible

output "pet-name" {
  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}